### PR TITLE
Using random_int to generate cryptographic random

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- To generate the random integers cryptographically, using the `random_int` to replace the `mt_rand` function.

### CODE REVIEW

**Comment by ankurk91** [comment]
https://stackoverflow.com/questions/4356289/php-random-string-generator#answer-31107425

**Comment by ankurk91** [comment]
https://stackoverflow.com/questions/4356289/php-random-string-generator#answer-31107425

**Comment by pH-7** [comment]
Excellent! Thanks very much for doing this @peter279k 
BTW, I think there is one more place where we can also replace `mt_rand`, it's in `Password.php` https://github.com/pH-7/passcode-password-generator/blob/main/src/Generator/Password.php#L28 since `array_rand` is also using `mt_rand` :)

**Comment by pH-7** [comment]
For anyone interested, I've made a video about this too - https://www.youtube.com/watch?v=Z5CQxhAb2CU 🚀

Enjoy! 🎉

**Pull request merged**
